openapi: '3.0.2'
info:
  title: Authentication Api
  version: '1.0.0'
servers:
  - url: https://localhost:3000/v1
paths:
  /login:
    post:
      description: submit login data here
      parameters:
      - name: login data
        in: query
        description: username & password of the login user
        required: true
        schema:
          type: object
          required:
            - "user"
            - "pass"
          properties:
            user:
              type: string
            pass:
              type: string
      responses:
        '200':
          description: successful login
          content:
              application/json:
                example: { "user": "karl", "pass": "franz" }

